config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  authenticate :user do
    resources :users, except: %i[create destroy]
    resources :leave_requests, except: %i[edit update show destroy] do
      member do
        post "approve_request", to: "leave_requests#approve"
        post "decline_request", to: "leave_requests#decline"
      end
    end

    post 'create_user', to: 'users#create'
    delete 'remove_user/:id', to: 'users#destroy', as: :remove_user

    root "home#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave_request.rb
# == Schema Information
#
# Table name: leave_requests
#
#  id             :bigint           not null, primary key
#  category       :integer          default(0), not null
#  leave_end_at   :datetime
#  leave_start_at :datetime
#  reason         :text
#  status         :integer          default(0), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :bigint
#
# Indexes
#
#  index_leave_requests_on_user_id  (user_id)
#
class LeaveRequest < ApplicationRecord
  belongs_to :user

  enum status: %i[pending declined approved]
  enum category: %i[vacation_leave sick_leave]

  validates :reason, :leave_end_at, :leave_start_at, presence: true
  validate :ensure_date_not_overlapped, on: :create

  def leave_in_days
    days = (leave_end_at.to_date - leave_start_at.to_date).to_i + 1
    return 1 if days.zero?

    days
  end

  private

  def ensure_date_not_overlapped
    return unless leave_start_at || leave_end_at

    not_less_than_today = leave_start_at.to_date >= Time.zone.today
    valid_date_range = leave_start_at.to_date <= leave_end_at.to_date
    return if not_less_than_today && valid_date_range

    errors.add(:base, "Leave Dates Overlapped")
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  leave_credits          :integer          default(0)
#  name                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer          default("employee"), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  enum role: %i[employee hr_staff super_admin]

  has_many :leave_requests, dependent: :destroy

  validates :name, :role, presence: true
  validates :name, uniqueness: true
  validates :email, uniqueness: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    user = resource
    if user.super_admin? || user.hr_staff?
      users_path
    else
      user_path(user)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  before_action :initialize_categories, only: %i[new create]
  before_action :find_request, only: %i[approve decline]

  def index
    @requests = LeaveRequest.joins(:user).all
  end

  def new
    @request = LeaveRequest.new
  end

  def create
    request = current_user.leave_requests.new(leave_requests_params)

    if request.save
      redirect_to user_path(current_user), notice: "Leave Request Successfully Filed"
    else
      @request = LeaveRequest.new(leave_requests_params)
      flash[:alert] = request.errors.full_messages.to_sentence
      render :new
    end
  end

  def approve
    @request.approved!
    user = @request.user
    user.update(leave_credits: user.leave_credits - @request.leave_in_days)

    redirect_to leave_requests_path, notice: "Leave Successfully Approved"
  end

  def decline
    @request.declined!

    redirect_to leave_requests_path, notice: "Leave Successfully Declined"
  end

  private

  def leave_requests_params
    params.require(:leave_request)
          .permit(:category, :reason, :leave_start_at, :leave_end_at)
  end

  def initialize_categories
    @categories = LeaveRequest.categories
                              .map { |k, _v| [k.gsub('_', ' ').titleize, k] }
  end

  def find_request
    @request = LeaveRequest.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :initialize_roles, only: %i[new create edit update]
  before_action :find_user, only: %i[edit update destroy]

  def index
    users = User.all.where.not(id: current_user.id)

    @users = if current_user.super_admin?
               users
             else
               users.where.not(role: "super_admin")
             end
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
    @requests = @user.leave_requests
  end

  def edit
  end

  def update
    if @user.update(sanitized_user_params)
      redirect_to users_path, notice: "User Successfully Updated"
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def create
    unless user_params[:password] == user_params[:password]
      flash[:alert] = 'Password Should Match'
      render :new
    end

    user = User.new(user_params.reject! { |k| k == :confirm_password })
    if user.save
      redirect_to users_path, notice: 'User Successfully Created'
    else
      flash[:alert] = user.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    if @user
      @user.destroy!
      flash[:notice] = "User Successfully Deleted"
    else
      flash[:alert] = "User Not Found"
    end
    redirect_to users_path
  end

  private

  def user_params
    {
      role: params[:role],
      name: params[:name],
      email: params[:email],
      password: params[:password],
      confirm_password: params[:confirm_password],
      leave_credits: params[:leave_credits]
    }
  end

  def initialize_roles
    roles = User.roles
    user_based_roles = if current_user.super_admin?
                         roles
                       else
                         roles.reject { |k, _v| k == "super_admin" }
                       end
    @roles = user_based_roles.map { |k, _v| [k.gsub('_', ' ').titleize, k] }
  end

  def find_user
    @user = User.find(params[:id])
  end

  def sanitized_user_params
    params.require(:user).permit(:name, :role, :email, :leave_credits)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def has_leave_credits?(credits)
    !credits.zero?
  end

  def to_short_date(date)
    format = "%B %d, %Y"
    date.strftime(format)
  end
end

app/views/home/index.html.erb
<%= provide(:title, "Home") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeMonitoringVenteney</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/leave_requests/index.html.erb
<%= render "shared/flash" %>

<div class="card px-4 py-4">
  <h1 class="title">Leave Requests</h1>

  <div class="card mt-6">
    <header class="card-header">
      <p class="card-header-title">
        Leave Requests
      </p>
    </header>

    <div class="card-content">
      <table class="table is-fullwidth is-hoverable">
        <thead>
          <tr>
            <td>Type</td>
            <td>User Email</td>
            <td>Reason</td>
            <td>Start Date</td>
            <td>End Date</td>
            <td>No. of Days</td>
            <td>Status</td>
            <td>Actions</td>
          </tr>
        </thead>

        <tbody>
          <% @requests.each do |req| %>
            <tr>
              <td><%= req.category.titleize %></td>
              <td><%= req.user.email %></td>
              <td><%= req.reason %></td>
              <td><%= to_short_date req.leave_start_at %></td>
              <td><%= to_short_date req.leave_end_at %></td>
              <td><%= req.leave_in_days %></td>
              <td><%= req.status.titleize %></td>
              <td>
                <% if req.pending? %>
                  <div class="is-flex">
                    <div class="mr-2">
                      <%= link_to "Approve",
                        approve_request_leave_request_path(req),
                        method: :post,
                        class: "button is-link is-light has-background-success has-text-primary-light"
                      %>
                    </div>

                    <div>
                      <%= link_to "Decline",
                        decline_request_leave_request_path(req),
                        method: :post,
                        class: "button is-link is-light has-background-danger has-text-primary-light"
                      %>
                    </div>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/leave_requests/new.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/flash" %>

    <div class="title has-text-centered">File Leave Request</div>

    <%= form_with model: @request, local: true do |f| %>
      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :category, "Leave Type", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.select :category,  @categories, {}, { class: "select" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :reason, "Reason", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.text_field :reason,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :leave_start_at, "Start Date", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.date_field :leave_start_at,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :leave_end_at, "End Date", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.date_field :leave_end_at,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit "Create", class: "button is-link" %>
        </div>

        <div class="control">
          <%= link_to "Cancel", user_path(current_user), class: "button is-link is-light" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_flash.html.erb
<div class="column">
  <% flash.each do |type, msg| %>
    <article
      class="message <%= type == 'notice' ? 'is-success' : 'is-danger' %>"
    >
      <div class="message-header">
        <p><%= msg %></p>
      </div>
    </article>
  <% end %>
</div>

app/views/users/edit.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/flash" %>

    <div class="title has-text-centered">Update User</div>

    <%= form_with model: @user, local: true do |f| %>
      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :role, "Employee Role", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.select :role,  @roles, {}, { class: "select" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :name, "Employee Name", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.text_field :name,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :email, "Employee Email", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.email_field :email,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :leave_credits, "Employee Leave Credits", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.number_field :leave_credits, { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit "Update", class: "button is-link" %>
        </div>

        <div class="control">
          <%= link_to "Cancel", users_path, class: "button is-link is-light" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<%= render "shared/flash" %>

<h1 class="title">Employees</h1>
<div class="is-flex mb-4">
  <div class="mr-4">
    <%= link_to "Add Employee", new_user_path, class: "button is-link is-light" %>
  </div>

  <% if current_user.hr_staff? %>
    <div>
      <%= link_to "Leave Requests", leave_requests_path, class: "button is-link is-light" %>
    </div>
  <% end %>
</div>

<table class="table">
  <thead>
    <tr>
      <td>Name</td>
      <td>Email</td>
      <td>Role</td>
      <td>Leave Credits</td>
      <td>Actions</td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.leave_credits %></td>
        <td><%= link_to "Edit", edit_user_path(user), class: "button is-link is-small" %></td>
        <td><%= link_to "Remove", remove_user_path(user), method: :delete, class: "button is-danger is-small" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<section class="section">
  <div class="container">
    <%= render "shared/flash" %>

    <div class="title has-text-centered">Add User</div>

    <%= form_with url: create_user_path, local: true do |f| %>
      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :role, "Employee Role", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.select :role,  @roles, {}, { class: "select" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :name, "Employee Name", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.text_field :name,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :email, "Employee Email", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.email_field :email,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :leave_credits, "Employee Leave Credits", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.number_field :leave_credits, { value: 0, class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :password, "Password", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.password_field :password,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
          <%= f.label :confirm_password, "Confirm Password", class: "label" %>
        </div>

        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.password_field :confirm_password,  { class: "input" } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit "Create", class: "button is-link" %>
        </div>

        <div class="control">
          <%= link_to "Cancel", users_path, class: "button is-link is-light" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<%= render "shared/flash" %>

<div class="card px-4 py-4">
  <h1 class="title">Employee Details</h1>

  <div class="is-flex">
    <div class="mr-1 has-text-weight-medium">Name: </div>
    <div><%= @user.name.titleize %></div>
  </div>


  <div class="is-flex">
    <div class="mr-1 has-text-weight-medium">Email: </div>
    <div><%= @user.email %></div>
  </div>

  <div class="is-flex">
    <div class="mr-1 has-text-weight-medium">Remaining Leave Credits: </div>
    <div><%= @user.leave_credits %></div>
  </div>

  <div class="card mt-6">
    <header class="card-header">
      <p class="card-header-title">
        Leave Requests
      </p>

      <% if has_leave_credits?(@user.leave_credits) %>
        <%= link_to "File Leave Request", new_leave_request_path, class: "button is-link is-small mx-2 my-2" %>
      <% end %>
    </header>

    <div class="card-content">
      <table class="table is-fullwidth is-hoverable">
        <thead>
          <tr>
            <td>Type</td>
            <td>Reason</td>
            <td>Start Date</td>
            <td>End Date</td>
            <td>No. of Days</td>
            <td>Status</td>
          </tr>
        </thead>

        <tbody>
          <% @requests.each do |req| %>
            <tr>
              <td><%= req.category.titleize %></td>
              <td><%= req.reason %></td>
              <td><%= to_short_date req.leave_start_at %></td>
              <td><%= to_short_date req.leave_end_at %></td>
              <td><%= req.leave_in_days %></td>
              <td><%= req.status.titleize %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>